const S=document.createElement('style');S.textContent='.rh{position:fixed;right:25px;top:22px;z-index:12;text-align:right;color:#ddc77e;font:14px Georgia}.rh b{font-size:25px;color:white}.up{position:fixed;inset:0;z-index:30;display:grid;place-items:center;background:#030506ed}.up.hide{display:none}.cards{display:flex;gap:18px}.card{width:220px;padding:24px;background:#11161b;color:#ddd;border:1px solid #927e47;font:16px Georgia}.card b{display:block;color:#f1d486;margin-bottom:12px}.card:hover{transform:translateY(-7px);box-shadow:0 0 35px #d4aa4444}';document.head.appendChild(S);document.body.insertAdjacentHTML('beforeend','<div class="rh"><b id="rn">ROUND 1 / 7</b><br><span id="lvl">LEVEL 1 · 0 RUNES</span></div><div class="up hide" id="up"><div><h1>CHOOSE A BLESSING</h1><div class="cards" id="cards"></div></div></div>');
const BR=reset,BU=update,BD=draw,BF=finish,BH=playerHurt;let w=1,lv=1,xp=0,need=80,runes=0,busy=0,P={d:1,h:100,s:100,arm:0,crit:.08,leech:0,spd:1};const R=[['BROKEN VANGUARD',3,85,0],['HOUNDS OF VEIL',5,95,0],['PURPLE OATHSWORN',4,145,0],['PALE WARDEN',1,620,1],['LEGION OF ASH',7,155,0],['WARDENS TWAIN',2,520,1],['NIGHTFALL KING',1,1250,1]];const U=[['TEMPERED STEEL','공격력 +25%',()=>P.d+=.25],['VIGOR','최대 체력 +30',()=>{P.h+=30;p.hp=P.h}],['ENDLESS BREATH','스태미나 +30',()=>{P.s+=30;p.st=P.s}],['BLOOD DRINKER','흡혈 +8%',()=>P.leech+=.08],['STONE WARD','피해 감소 +18%',()=>P.arm=Math.min(.6,P.arm+.18)],['ASSASSIN','치명타 +15%',()=>P.crit+=.15],['SWIFT ASH','이동 속도 +14%',()=>P.spd+=.14],['GOLDEN FLASK','성배병 +2',()=>p.flask+=2]];
function gain(n){runes+=n;xp+=n;if(xp>=need){xp-=need;lv++;need=Math.floor(need*1.3);P.d+=.1;P.h+=10;p.hp=P.h;message('LEVEL '+lv+' · POWER AWAKENED',1300)}}
function startRound(){busy=0;enemies=[];let r=R[w-1];p.x=W*.22;p.y=H*.72;p.hp=Math.min(P.h,p.hp+P.h*.3);p.st=P.s;for(let i=0;i<r[1];i++){let e=spawn(W*(.7+Math.cos(i*2.2)*.13),H*(.67+Math.sin(i*1.8)*.15),r[3]);e.hp=e.max=r[2];e.reward=25+w*10;e.elite=w==3||w>=5;e.attackMax*=Math.max(.7,1-w*.04)}$('#boss').classList.toggle('on',!!r[3]);$('#boss').firstElementChild.textContent=r[0];run=1;message('ROUND '+w+' · '+r[0],1700);ui()}
function offer(){run=0;let b=$('#cards');b.innerHTML='';[...U].sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let c=document.createElement('button');c.className='card';c.innerHTML='<b>'+u[0]+'</b>'+u[1];c.onclick=()=>{u[2]();$('#up').classList.add('hide');w++;startRound()};b.appendChild(c)});$('#up').classList.remove('hide')}
reset=function(){BR();w=1;lv=1;xp=0;need=80;runes=0;busy=0;P={d:1,h:100,s:100,arm:0,crit:.08,leech:0,spd:1};startRound();run=0};
strike=function(e,n){if(e.dead||e.lastHit===attackSeq)return;e.lastHit=attackSeq;let cr=Math.random()<P.crit,v=Math.round(n*P.d*(cr?1.8:1));e.hp-=v;e.hurt=.22;shake=cr?18:9;burst(e.x,e.y,cr?'#ffe080':e.elite?'#b45cff':'#bd3b43',cr?45:24,280);p.hp=Math.min(P.h,p.hp+v*P.leech);if(cr)message('GOLDEN CRITICAL · '+v,650);if(e.hp<=0){e.dead=1;gain(e.reward);burst(e.x,e.y,'#c5e8ff',50,300);if(!enemies.some(q=>!q.dead)&&!busy){busy=1;run=0;if(w==R.length)setTimeout(()=>finish(1),800);else setTimeout(offer,700)}}};
playerHurt=(n,e)=>BH(Math.max(1,Math.round(n*(1-P.arm))),e);
update=function(dt){let x=p.x,y=p.y;BU(dt);p.x=x+(p.x-x)*P.spd;p.y=y+(p.y-y)*P.spd;p.st=Math.min(P.s,p.st);for(let e of enemies)if(e.elite&&Math.random()<dt*7)burst(e.x,e.y-30,'#a94ee8',1,25)};
draw=function(){BD();let g=X.createLinearGradient(0,H*.45,0,H);g.addColorStop(0,'transparent');g.addColorStop(1,'#02040aaa');X.fillStyle=g;X.fillRect(0,0,W,H);for(let e of enemies)if(!e.dead&&e.elite){X.strokeStyle='#b55cff55';X.lineWidth=4;X.beginPath();X.ellipse(e.x,e.y-20,e.r*1.8,e.r*.7,0,0,7);X.stroke()}};
ui=function(){if(!p)return;$('#hp').style.width=100*p.hp/P.h+'%';$('#st').style.width=100*p.st/P.s+'%';$('#status').innerHTML='FLASK × '+p.flask+'<br>POWER ×'+P.d.toFixed(2)+' · ARMOR '+Math.round(P.arm*100)+'%';let b=enemies.find(e=>e.boss&&!e.dead);if(b)$('#bossHp').style.width=100*b.hp/b.max+'%';$('#rn').textContent='ROUND '+w+' / 7';$('#lvl').textContent='LEVEL '+lv+' · '+runes+' RUNES'};
finish=function(v){if(!v)return BF(0);BF(1);setTimeout(()=>{$('#endTitle').textContent='NIGHTFALL CONQUERED';$('#endText').textContent='Seven trials broken. Level '+lv+' · '+runes+' runes claimed.'},720)};document.querySelector('.sub').textContent='COVENANT ASCENDANT';