const ws=document.createElement('style');ws.textContent='.weaponhud{position:fixed;z-index:14;left:25px;bottom:92px;color:#d9c37d;font:13px Georgia;line-height:1.8}.weaponhud b{color:#fff;font-size:18px}.weaponhud span{color:#89919a}.weaponhud .active{color:#f0d27c}';document.head.appendChild(ws);document.body.insertAdjacentHTML('beforeend','<div class="weaponhud"><b id="weaponName">LONGSWORD</b><br><span id="weaponKeys"><i class="active">1 SWORD</i> · 2 SPEAR · 3 GREAT AXE · 4 STAFF</span></div>');
const weapons=[{n:'LONGSWORD',mul:1,range:0,c:'#dff8ff'},{n:'MOON SPEAR',mul:.82,range:68,c:'#70d9ff'},{n:'GREAT AXE',mul:1.65,range:22,c:'#ff9b58'},{n:'ARCANE STAFF',mul:.72,range:0,c:'#b86dff'}];let weapon=0,shots=[],enemyShots=[],dashTrail=[],dashPulse=[];
function setWeapon(i){weapon=i;$('#weaponName').textContent=weapons[i].n;[...$('#weaponKeys').children].forEach((e,j)=>e.classList.toggle('active',j===i));message(weapons[i].n,500);sound(250+i*100,.12,'triangle')}
addEventListener('keydown',e=>{let i=+e.key-1;if(i>=0&&i<4)setWeapon(i)});
const oldAttack=doAttack;doAttack=function(h){if(weapon===3&&!h&&run&&!p.attack&&!p.roll&&p.st>=20){p.st-=20;p.attack=p.attackMax=.38;attackSeq++;shots.push({x:p.x,y:p.y-28,vx:Math.cos(p.ang)*520,vy:Math.sin(p.ang)*520,life:1.3,r:10});burst(p.x,p.y-28,'#bb71ff',24,120);sound(620,.25,'sine',.08);return}oldAttack(h)};
const oldStrike=strike;strike=function(e,n){oldStrike(e,n*weapons[weapon].mul)};
const oldBegin=startRound;startRound=function(){oldBegin();enemies.forEach((e,i)=>{e.kind=e.boss?'boss':(i+w)%4;e.cool=1+Math.random();if(e.kind===2)e.max=e.hp=Math.round(e.max*1.45)})};
const oldRoll=roll;roll=function(){let was=p.roll;oldRoll();if(!was&&p.roll){dashPulse.push({x:p.x,y:p.y,r:8,life:.45});for(let i=0;i<28;i++)burst(p.x,p.y,i%3?'#7fd8ff':'#ffffff',1,220);sound(110,.3,'sawtooth',.08)}};
const oldUpdate2=update;update=function(dt){oldUpdate2(dt);if(p.roll&&Math.random()<dt*75)dashTrail.push({x:p.x,y:p.y,a:p.ang,life:.34});dashTrail.forEach(t=>t.life-=dt);dashTrail=dashTrail.filter(t=>t.life>0);dashPulse.forEach(q=>{q.life-=dt;q.r+=dt*240});dashPulse=dashPulse.filter(q=>q.life>0);
shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let e of enemies)if(!e.dead&&dist(s,e)<e.r+s.r){oldStrike(e,38);s.life=0;burst(s.x,s.y,'#c77bff',28,230)}});shots=shots.filter(s=>s.life>0);
for(let e of enemies){if(e.dead||e.boss)continue;e.cool-=dt;if((e.kind===1||e.kind===3)&&dist(e,p)<360){let a=Math.atan2(p.y-e.y,p.x-e.x);if(dist(e,p)<210){e.x-=Math.cos(a)*70*dt;e.y-=Math.sin(a)*70*dt}if(e.cool<=0){let sp=e.kind===1?300:220;enemyShots.push({x:e.x,y:e.y-25,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:2.3,r:e.kind===1?5:11,magic:e.kind===3});e.cool=e.kind===1?1.6:2.2;sound(e.kind===1?290:150,.15,'triangle',.035)}}}
enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(dist(s,p)<22+s.r){playerHurt(s.magic?22:14,{attack:0,stagger:0,boss:0});s.life=0;burst(s.x,s.y,s.magic?'#b85cff':'#e9c779',18,180)}});enemyShots=enemyShots.filter(s=>s.life>0);
if(p.attack&&weapon===1){let z=1-p.attack/p.attackMax;if(z>.32&&z<.64)enemies.forEach(e=>{if(!e.dead&&dist(p,e)<145+e.r){let a=Math.atan2(e.y-p.y,e.x-p.x),d=Math.atan2(Math.sin(a-p.ang),Math.cos(a-p.ang));if(Math.abs(d)<.42)oldStrike(e,26)}})}
if(p.attack&&weapon===2){let z=1-p.attack/p.attackMax;if(z>.44&&z<.72)enemies.forEach(e=>{if(!e.dead&&dist(p,e)<118+e.r)oldStrike(e,p.heavy?72:46)})}};
const oldDraw2=draw;draw=function(){oldDraw2();X.save();X.globalCompositeOperation='screen';dashTrail.forEach(t=>{X.globalAlpha=t.life*1.8;let g=X.createLinearGradient(t.x-Math.cos(t.a)*80,t.y-Math.sin(t.a)*80,t.x,t.y);g.addColorStop(0,'transparent');g.addColorStop(1,'#aeeaff');X.strokeStyle=g;X.lineWidth=18*t.life;X.beginPath();X.moveTo(t.x-Math.cos(t.a)*90,t.y-Math.sin(t.a)*90);X.lineTo(t.x,t.y);X.stroke()});dashPulse.forEach(q=>{X.globalAlpha=q.life;X.strokeStyle='#c9f4ff';X.lineWidth=4*q.life;X.beginPath();X.ellipse(q.x,q.y,q.r,q.r*.38,0,0,7);X.stroke()});
shots.forEach(s=>{X.globalAlpha=.9;X.shadowBlur=28;X.shadowColor='#b65cff';X.fillStyle='#e5c2ff';X.beginPath();X.arc(s.x,s.y,s.r,0,7);X.fill()});enemyShots.forEach(s=>{X.shadowBlur=18;X.shadowColor=s.magic?'#a339ff':'#e3b64b';X.fillStyle=s.magic?'#d086ff':'#ffe198';X.beginPath();X.arc(s.x,s.y,s.r,0,7);X.fill()});X.restore();
for(let e of enemies)if(!e.dead&&!e.boss){X.save();X.translate(e.x,e.y-55);X.textAlign='center';X.font='bold 10px Arial';X.fillStyle=e.kind===1?'#e9cf83':e.kind===2?'#f08c62':e.kind===3?'#c787ff':'#aeb8c0';X.fillText(['SWORD','ARCHER','BRUTE','HEXER'][e.kind],0,0);if(e.kind===1){X.strokeStyle='#d7b86d';X.beginPath();X.arc(15,15,15,-1.3,1.3);X.stroke()}if(e.kind===3){X.fillStyle='#a64cff';X.beginPath();X.arc(13,16,5,0,7);X.fill()}X.restore()}
let a=p.ang;X.save();X.translate(p.x,p.y-35);X.rotate(a);X.strokeStyle=weapons[weapon].c;X.shadowBlur=12;X.shadowColor=weapons[weapon].c;if(weapon===1){X.lineWidth=4;X.beginPath();X.moveTo(10,0);X.lineTo(82,0);X.stroke();X.fillStyle='#dff8ff';X.beginPath();X.moveTo(90,0);X.lineTo(74,-7);X.lineTo(74,7);X.fill()}else if(weapon===2){X.lineWidth=7;X.beginPath();X.moveTo(8,0);X.lineTo(55,0);X.stroke();X.fillStyle='#ff9b58';X.fillRect(48,-16,25,32)}else if(weapon===3){X.lineWidth=5;X.beginPath();X.moveTo(7,0);X.lineTo(66,0);X.stroke();X.fillStyle='#c67cff';X.beginPath();X.arc(68,0,9,0,7);X.fill()}X.restore()};
document.querySelector('.help').innerHTML+='<br><span class="key">1–4</span> SWITCH WEAPON · SPEAR / GREAT AXE / ARCANE STAFF';